---
title: "Tables 1-3"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE, results= 'hide'}
library(readxl)
library(dplyr)
library(gtsummary)
library(table1)

data <- read_excel("FellowEye.xlsx")
dt<- data[-c(1:2),]
dt_temp<- dt[,c(1:13, 16:21 ,99)]
dt_temp2<- dt[,c(1:13, 16:21 ,99)]
dt_temp <- sapply(dt_temp[c(1:20)], as.numeric)
dt_temp <-as.data.frame(cbind(dt_temp))

data_names<- c("Patient_code", "Left_Right", "Age", "Gender", "KC_fam_his", "myopia_astig_fam_his", "Ethnicity", "Atopic", "Other_sys_dis", "eye_rubbing", "disease_duration", "corneal_trans", "prev_lasik", "worse_eye", "contact_use", "apical", "vogt_striae", "fleischer_ring", "cone_observed", "CXL_choice") 
names(dt_temp)<- data_names
dt_fin<- dt_temp %>% filter(prev_lasik==0)

#create a CXL column
dt_fin<- dt_fin %>% mutate(CXL_fellow= ifelse(Left_Right==CXL_choice, "Bilateral", "Unilateral"))
table(dt_fin$CXL_fellow)

#create fam history variable
dt_fin<- dt_fin %>% mutate(family_history= ifelse(myopia_astig_fam_his==1, "Myopia/ astigmatism", ifelse(KC_fam_his==1, "KCN", ifelse(is.na(dt_fin$KC_fam_his), NA, "None"))))
#make factor variables
dt_fin$Gender<- as.factor(dt_fin$Gender)
levels(dt_fin$Gender) <- c("Male", "Female")
levels(dt_fin$Gender) #check
dt_fin$Ethnicity<- as.factor(dt_fin$Ethnicity)
levels(dt_fin$Ethnicity) <- c("Caucasian", "African American", "South Asian", "East Asian", "Hispanic")
levels(dt_fin$Ethnicity)
label(dt_fin$family_history)= "Family History"

hist(dt_fin$Age) #skew= use median

#https://cran.r-project.org/web/packages/gtsummary/readme/README.html
#table 1: age, gender, fam history, ethnicity

tb1<- dt_fin %>% select(Age, Gender, family_history, Ethnicity, CXL_fellow) 

#table 2: right/left, disease duration, atopic disease, eye rubbing, contact use and type, apical scar, vogt straie, cone observed clinically

hist(dt_fin$disease_duration) #skewed- use median

dt_fin$CXL_choice<- as.factor(dt_fin$CXL_choice)
levels(dt_fin$CXL_choice) <- c("Right", "Left")
dt_fin$contact_use<- as.factor(dt_fin$contact_use)
levels(dt_fin$contact_use) <- c("None", "Scleral", "RGP", "Soft")
dt_fin$dt_fin$Atopic<- as.factor(dt_fin$Atopic)
levels(dt_fin$Atopic) <- c("No", "Yes")
dt_fin$eye_rubbing<- as.factor(dt_fin$eye_rubbing)
levels(dt_fin$eye_rubbing) <- c("No", "Yes")
dt_fin$apical<- as.factor(dt_fin$apical)
levels(dt_fin$apical) <- c("No Scarring", "Apical Scarring")
dt_fin$vogt_striae <-  as.factor(dt_fin$vogt_striae)
levels(dt_fin$vogt_striae) <- c("No", "Yes")
dt_fin$cone_observed <-  as.factor(dt_fin$cone_observed)
levels(dt_fin$cone_observed) <- c("No", "Yes")

label(dt_fin$CXL_choice)= "Eye"
label(dt_fin$disease_duration)= "Disease Duration"
label(dt_fin$eye_rubbing)= "Eye Rubbing"
label(dt_fin$contact_use)= "Contact Lenses Use and Type"
label(dt_fin$apical)= "Apical Scar"
label(dt_fin$Atopic)= "Atopic Disease"
label(dt_fin$vogt_striae)= "Vogt Striae"
label(dt_fin$cone_observed)= "Cone Observed Clinically"

tb2<- dt_fin %>% select(CXL_choice, disease_duration, Atopic, eye_rubbing, contact_use, apical,vogt_striae, cone_observed, CXL_fellow) 

#table 3: K2, Km, front KMAX, pachymetry
#For people with proof of pentacam, use these values instead of the pre-operative 

table3_dt<- dt[,c(2, 13, 35, 36, 48, 55, 70, 71, 83, 90, 99)]
names(table3_dt)<- c("Left_Right", "prev_lasik", "K2_pre", "KM_pre", "Patchy_thin_pre", "K_max_front_pre", "K2_pentacam", "KM_pentacam", "Patchy_thin_pentacam", "K_max_front_pentacam", "CXL_choice")

#make everything numeric
table3_dt <- sapply(table3_dt, as.numeric)
table3_dt <-as.data.frame(cbind(table3_dt))
#take out previous lasik
table3_dt<- table3_dt %>% filter(prev_lasik==0)
#create a CXL column
table3_dt<- table3_dt %>% mutate(CXL_fellow= ifelse(Left_Right==CXL_choice, "Bilateral", "Unilateral"))
#if pentacam exists, use this value
table3_dt<- table3_dt %>% mutate(K2 = ifelse(is.na(K2_pentacam)== FALSE, K2_pentacam, K2_pre))
table3_dt<- table3_dt %>% mutate(KM = ifelse(is.na(KM_pentacam)== FALSE, KM_pentacam, KM_pre))
table3_dt<- table3_dt %>% mutate(Front_Kmax = ifelse(is.na(K_max_front_pentacam)== FALSE, K_max_front_pentacam, K_max_front_pre))
table3_dt<- table3_dt %>% mutate(Patchy_thin = ifelse(is.na(Patchy_thin_pentacam)== FALSE, Patchy_thin_pentacam, Patchy_thin_pre))
tb3<- table3_dt %>% select(K2, KM, Front_Kmax, Patchy_thin, CXL_fellow)

hist(tb3$K2) #skewed
hist(tb3$KM) #skewed
hist(tb3$Front_Kmax) #skewed
hist(tb3$Patchy_thin) #skewed

label(tb3$KM)= "Km"
label(tb3$Front_Kmax)= "Front Kmax"
label(tb3$Patchy_thin)= "Pachymetry at thinnest point"
```


**Table 1**
```{r tables1, message=FALSE, echo= FALSE, warning=FALSE}
#t.test
tbl_summary(tb1, by= CXL_fellow) %>% add_p(test= list(all_continuous() ~ "t.test")) %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**")%>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")

#wilcoxon
tbl_summary(tb1, by= CXL_fellow) %>% add_p() %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**")%>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")
```

**Table 2**
```{r tables2, message=FALSE, echo= FALSE, warning=FALSE}
#t.test
tbl_summary(tb2, by= CXL_fellow) %>% add_p(test= list(all_continuous() ~ "t.test")) %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**")%>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")

#wilcoxon
tbl_summary(tb2, by= CXL_fellow) %>% add_p() %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**")%>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")
```

**Table 3**
```{r tables3, message=FALSE, echo= FALSE, warning=FALSE}
#t.test
tbl_summary(tb3, by= CXL_fellow) %>% add_p(test= list(all_continuous() ~ "t.test")) %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**") %>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")

#wilcoxon
tbl_summary(tb3, by= CXL_fellow) %>% add_p() %>% modify_header(label = "**Variable**") %>% bold_labels() %>% modify_spanning_header(starts_with("stat_") ~ "**CXL Type**") %>% modify_footnote(update = starts_with("stat_") ~ "median (IQR) for continuous variables; n (%) categorical variables")

wilcox.test(K2~ CXL_fellow, data = tb3)
wilcox.test(KM~ CXL_fellow, data = tb3)
wilcox.test(Front_Kmax~ CXL_fellow, data = tb3)
wilcox.test(Patchy_thin~ CXL_fellow, data = tb3)

t.test(K2~ CXL_fellow, data = tb3)
t.test(KM~ CXL_fellow, data = tb3)
t.test(Front_Kmax~ CXL_fellow, data = tb3)
t.test(Patchy_thin~ CXL_fellow, data = tb3)
```


